### ISSUE TITLE
Loading Risk analysis from view menu, using complete example throws an error

### ISSUE THREAD

**Issue by nigel-v-thomas** [failys/cairis#1]
See attached screen shot of error
![mysql error cairis](https://f.cloud.github.com/assets/1025109/994411/176fe10c-09ac-11e3-953a-98393d3ba755.png)

**Comment by failys** [comment]
Closing this issue as I think general maintenance updates might have resolved this.  Please do reopen if this is still an issue though.

**Comment by failys** [comment]
I'm re-opening this, as this issues seems to have cropped up in the Risks web services API test running on Travis.

**Comment by failys** [comment]
Tests on travis now run successfully.  Closing issue.
