### ISSUE TITLE
Tensions are not stored properly in some cases.

### ISSUE THREAD

**Issue by RafVandelaer** [failys/CAIRIS#10]
The problem mostly occurs when there are some tension fields in the last column are " ". When you update these tensions and reopen them, they don't have the same values.

This is an example of what happens.

Firstly I alter the tensions
![1](https://cloud.githubusercontent.com/assets/8038014/7726136/eb8d5310-fef7-11e4-90a9-cb73c7037af4.PNG)

After updating the environment and closing all of the environment windows, I reopen the window and the tensions values are changed to the following sequence.
It seems that the third column is copied to the last column.
![4](https://cloud.githubusercontent.com/assets/8038014/7726332/234e2c42-fef9-11e4-8474-dd52fc8b1891.PNG)

**Comment by failys** [comment]
This should now be fixed.

**Comment by RafVandelaer** [comment]
Problem is fixed.
Thank you!
