### ISSUE TITLE
CAIRIS Installation Instructions

### ISSUE THREAD

**Issue by willproctor** [failys/cairis#12]
# Installation problems

I've found a few problems installing CAIRIS on Ubuntu 14.04 LTS - fixes inline.

## Step 1:
```bash
sudo apt-get install python-wxglade python-glade2 python-wxgtk2.8 python-dev build-essential mysql-server mysql-client graphviz docbook dblatex python- pip git libmysqlclient-dev --no-install-recommends texlive-latex-extra docbook-utils
```
Should be python-pip. Also we have an unsatisfied dependency on python-numpy. Pip installation fails without it's own dependencies, so we should just install the package.
 

## Step 4:
```bash
$ sudo chown -R $CAIRIS_USER:$CAIRIS_USER $CAIRIS_DIR $ sudo chmod -R 775 $CAIRIS_DIR
```
Needs to be split at the $
 

## Step 6:
```bash
$ mysql –u cairis –p –database=cairis < $CAIRIS_SQL/procs.sql
$ mysql –u cairis –p –database=cairis < $CAIRIS_SQL/init.sql
```

Should be
```bash
$ mysql –u cairis –p cairis < $CAIRIS_SQL/procs.sql
$ mysql –u cairis –p cairis < $CAIRIS_SQL/init.sql
```

**Comment by failys** [comment]
Pushed fixes to the website (i.e. the gh-pages branch) to address these issues.  
The SQL scripts in step 6 were also being called in the wrong order top (init.sql should be called before proc.sql), so I fixed that at the same time.

**Comment by willproctor** [comment]
Slight update - help M. Salamon to install today - procs need to be installed first as there is a dependency in the init script. Otherwise we get a silent failure on the db setup scripts, and will be iterating over a null object in the DB when cairis is started.

mysql -h localhost -u cairis -p cairis < $CAIRIS_SQL/procs.sql
mysql -h localhost -u cairis -p cairis < $CAIRIS_SQL/init.sql

**Comment by failys** [comment]
[re-opening this issue]

Running procs.sql before init.sql should work, but I don't see how init.sql should be failing.  All init.sql does is create some table (ok - a lot tables), views, and populate a small number of tables with meta-data needed by CAIRIS.  Logically, it makes sense to run this first.

Can you please provide a bit more detail on the error received when running up CAIRIS if you call init.sql before procs.sql?

**Comment by failys** [comment]
Ok - I've found the problem.  A function is called in one of the views in init.sql.  I'll define this function in init.sql, and close this issue once done.

**Comment by failys** [comment]
This problem should now be fixed.

**Comment by failys** [comment]
Closing issue as this problem seems to be resolved.
