### ISSUE TITLE
Missing encodeURIComponent on "Export Model"

### ISSUE THREAD

**Issue by 4669842** [failys/cairis#136]
https://github.com/failys/cairis/blob/c5be64123c6f089964fba1ec927d4e62a8311162/cairis/web/dist/js/cairis/fileExport.js#L22
### Expected behaviour

- AJAX sends a GET request to exportUrl for data matching session_id, 
- AJAX parses a successful response using XMLHttpRequest
- AJAX completes parsing the XML document and downloads it locally.

### Actual behaviour
>AJAX has processData enabled automatically making any data object processed and transformed into a query string fitting to the default content-type "application/x-www-form-urlencoded"
>>$("#exportClick") is not encoded with "encodeURIComponent"like other functions in the JavaScript file which causes issues when AJAX parses "&" on exporting model.
>>"XML Parsing Error: not well-formed Location"  
and
"SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data."
thrown from
https://github.com/failys/cairis/blob/c5be64123c6f089964fba1ec927d4e62a8311162/cairis/web/dist/js/cairis/fileExport.js#L40

This stops the parsing process completely no XML file is downloaded.

### Steps to reproduce the behaviour

Parsing issues occur when "&" is placed in a "persona->activity" although I assume bug persists if "&" is inserted anywhere on the model which gets parsed through jquery.ajax when pressing "Export Model"

"Without encodeURIComponent the ampersand could be interpreted on the server as the start of a new field and jeopardize the integrity of the data." 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent
http://www.codecodex.com/wiki/Escape_sequences_and_escape_characters#XML 

## Another method
>"If you want to send a DOMDocument, or other non-processed data, set this option to false.
source: http://api.jquery.com/jQuery.ajax/"
#**processData:false,** // Prevents incorrect encoding ** 
https://github.com/failys/cairis/blob/c5be64123c6f089964fba1ec927d4e62a8311162/cairis/web/dist/js/cairis/fileExport.js#L26

### Version of CAIRIS
 1.3.1
### Operating Systems / Hardware 

Docker - ubuntu:zesty -

**Comment by failys** [comment]
Thanks for flagging this.  encodeURIComponent is missing in a few other places too, so I'll update the HTTP method calls and refactor where appropriate.
