### ISSUE TITLE
Requirements > Requirements Error

### ISSUE THREAD

**Issue by MLaverton** [failys/cairis#139]
### Expected behaviour
Create a requirement under the requirements tab, the requirement is saved and usable in other areas

### Actual behaviour
An error message is presented (image attached) and upon leaving the requirements section or changing Asset/Environment, the requirements are reset

![cairis requirements tab](https://user-images.githubusercontent.com/33700030/32854760-99e39c5a-ca37-11e7-92e2-8816d80697e1.PNG)

### Steps to reproduce the behaviour
Navigate to Requirements > Requirements, create a requirement and hit enter (produces error message)
Create a requirement and navigate to another area of the site, upon returning the requirement is no longer there.

### Version of CAIRIS
Latest (found on demo.cairis.org)

### Operating Systems / Hardware 
Windows 8, (using google chrome latest version)

**Comment by failys** [comment]
This should be fixed now.  I'll update demo.cairis.org when the Docker container is rebuilt, but if you have built CAIRIS from source you might want to try doing a git pull, clearing your web cache/history, and checking all is good.

**Comment by failys** [comment]
Docker containers updated and tested.  After you clear you cache/history and try again, the problem should be resolved.
