### ISSUE TITLE
Requirements row numbers

### ISSUE THREAD

**Issue by MLaverton** [failys/cairis#141]
### Expected behaviour
Id number of requirements to increment as new rows added

### Actual behaviour
Id number goes form 1 to 2, any rows added after are also numbered 2

### Steps to reproduce the behaviour
Add three or more rows to the requirements section under requirements

### Version of CAIRIS
demo.cairis.org

### Operating Systems / Hardware 
Windows 8
Google chrome latest version

**Comment by failys** [comment]
I don't seem to be able to reproduce this problem.  By 'Id', do you mean the number directly beneath the Add button?  Can you provide some screenshots and details of any browser errors in the console.  Also, if you export the model, are labels still numbered 2?

**Comment by MLaverton** [comment]
The yes that's the one, here is a screenshot of what I mean 
![image](https://user-images.githubusercontent.com/33700030/32896145-2970d75a-cada-11e7-96dd-4d173ac0aa68.png)

The numbers increment on each page refresh but once they are numbered this does not change.

These are the errors from the console:
![image](https://user-images.githubusercontent.com/33700030/32896257-70a70798-cada-11e7-815c-c46e982f10cd.png)

When generating the document the Id appears as follows
![image](https://user-images.githubusercontent.com/33700030/32896519-22a8613a-cadb-11e7-8cb3-272121294f77.png)

Let me know if you need anything else from me

**Comment by failys** [comment]
Can you please try:
1.  Adding a new requirement, completing the 'Requirement' column, and pressing return so the Success pop up appears.
2.  Repeating for a few other requirements

Are the labels now displayed correctly?

It appears to be possible to add, say, 3 requirements, but the only requirement that is added/updated is the row you are working in when you press return. As the label is generated by the client, you can get out-of-sync requirement labels. That's definitely a bug

There is an easy workaround for this 'label inconsistency' problem though. Just export and re-import the model. During the import process, the labels are then re-generated.

**Comment by failys** [comment]
I've just push an update which fixes a number of issues associated with adding/updating/deleting requirements associated with environments.  I've also removed the ability to add more than one requirements at a time, which may have played a part in this problem.  I'm closing this issue for now, but please re-open if this problem hasn't been resolved.
