### ISSUE TITLE
Chernoff faces overlap

### ISSUE THREAD

**Issue by MLaverton** [failys/cairis#142]
### Expected behaviour
Chernoff faces to present uniformly

### Actual behaviour
Some Chernoff faces overlap

### Steps to reproduce the behaviour
Create a number of requirements then go to Models > Requirements
![image](https://user-images.githubusercontent.com/33700030/32906028-ab32bbe6-caf3-11e7-84d2-6923ab21ea26.png)
The above may occur on some faces, there is no error in the console for this issue

### Version of CAIRIS
Latest (demo.cairis.org)

### Operating Systems / Hardware 
Windows 8
Google Chrome latest

**Comment by failys** [comment]
This isn't going to get fixed immediately, but there if you are using this model for documentation there is a workaround: use SVG Crowbar to export the model, edit the model in something like Inkscape so you can move the text, change the font, etc.

**Comment by failys** [comment]
Closing for now as there seems to be a viable workaround.
