### ISSUE TITLE
Creation of unnamed environments

### ISSUE THREAD

**Issue by LeoricDepewse** [failys/cairis#143]
### Expected behaviour
Should prevent the creation of unnamed environments.

### Actual behaviour
Button to create is greyed, but clicking it still allows the creation of an unnamed environment.
The created unnamed environment cannot be removed through the UI.

### Steps to reproduce the behaviour
Create an environment without naming it, ignoring greying of button.

### Version of CAIRIS
CAIRIS 1.3.2 commit 8cfca9c9db2a7325aa8b058742ecb9298279983a

**Comment by failys** [comment]
This particular issue is fixed, but this problem affects other objects as well.  I'll open a new issue for addressing this problem.
