### ISSUE TITLE
Move VM setup to scripted solution like Puppet/Chef

### ISSUE THREAD

**Issue by nigel-v-thomas** [failys/cairis#2]
It should be helpful to simplify the current install process, as there are myriad of little dependencies that need to be setup with the current install. 

I have setup a simple puppet script with dependencies to setup a VM machine.
See https://github.com/nigel-v-thomas/Vagrant_CAIRIS

**Comment by failys** [comment]
It's taken a while but CAIRIS is now available as a package on PyPI (installable via Pip). https://pypi.python.org/pypi/cairis.  A Debian package is also under development.
