### ISSUE TITLE
When a Task and Goal share an exact name

### ISSUE THREAD

**Issue by D-Dev** [failys/cairis#201]
### Expected behaviour
(This may or not be an issue, but is an observation)
If you start your CAIRIS journey with Tasks that you can then create/ breakdown into steps/goals (instead of having goals which are the operationalised by tasks) - There is a logic to say the Task is the Parent, and each step/goal is a child (of a parent/child, of a parent/child...) to achieve that task. 

However, to model this, we may start with a main task and we can create a matching main goal, under which has its sub-goals to complete the main goal. The task is however associated as a sub-goal of the main goal (rather than its parent).

### Actual behaviour
The logic is not entirely the question in this scenario. It is the observation that when the Task and main Goal share an identical name, only the Task is shown in the Goal model view with an arrow pointing back on itself. This is rectified when you go back in and change the goal name slightly. The Goal model now shows the Goal and the associated Task correctly.

I'm just not sure if this is a planned/desired behaviour, and/or the pro's and con's of keeping it this way if it is not. E.g. from a different point of view, does this solve the Task/Goal Parent/Child question to a degree visually, because the main goal and task are the same, as one.

### Steps to reproduce the behaviour
Steps as noted above.  I think I have left a couple of these examples linking back on itself in the Bravo view Goal model of TMN20180329.

### Version of CAIRIS
From Git Pull on 28 March 2018

### Operating Systems / Hardware 
Windows 7 with VMware using Ubuntu17 and Linux Chrome

**Comment by failys** [comment]
An example based on ACME Water would be useful.

The problem with one node being displayed (be this a task or a goal) when there are two nodes with the same name sounds like a 'feature' of graphviz, but there might be something we can do about this objects are created.

**Comment by failys** [comment]
Create goals/tasks with the same name in the UI shouldn't be allowed anymore.
