### ISSUE TITLE
Asset Model with Show Concerns

### ISSUE THREAD

**Issue by D-Dev** [failys/cairis#218]
### Expected behaviour
(Note to self - reduce title lengths)
When in Asset model (Charlie) view, with Show Concerns to Yes, I have a lot (probably too many). However, when I then tried to filter an asset, I received the browser 'something went wrong' error message.  I tried to filter another asset, and had another error message. The browser then froze, so I clicked a few times, and it did catch up after a few seconds and continue as normal.

### Actual behaviour
INFO:werkzeug:127.0.0.1 - - [30/Mar/2018 19:00:16] "GET /api/assets/model/environment/Charlie%20(Ops%20View)/asset/all?session_id=6f2J6MGkB5ZKdulWkf1rO76XUtREWrft&hide_concerns=0 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Mar/2018 19:01:36] "GET /api/assets/name/%28Alpha%29%20JChat?session_id=6f2J6MGkB5ZKdulWkf1rO76XUtREWrft HTTP/1.1" 200 -
(_mysql_exceptions.DataError) (1406, "Data too long for column 'head_name' at row 2") [SQL: u'call classTree(%s,%s)'] [parameters: (u'(Charlie) AHLTA-Theater F2-1', u'Charlie (Ops View)')] (Background on this error at: http://sqlalche.me/e/9h9h)
ERROR:cairisd:[404] Object not found: The model could not be found in the database
INFO:werkzeug:127.0.0.1 - - [30/Mar/2018 19:02:04] "GET /api/assets/model/environment/Charlie%20(Ops%20View)/asset/(Charlie)%20AHLTA-Theater%20F2-1?session_id=6f2J6MGkB5ZKdulWkf1rO76XUtREWrft&hide_concerns=0 HTTP/1.1" 404 -
(_mysql_exceptions.DataError) (1406, "Data too long for column 'head_name' at row 8") [SQL: u'call classTree(%s,%s)'] [parameters: (u'(Charlie) Air MEDEVAC', u'Charlie (Ops View)')] (Background on this error at: http://sqlalche.me/e/9h9h)
ERROR:cairisd:[404] Object not found: The model could not be found in the database
INFO:werkzeug:127.0.0.1 - - [30/Mar/2018 19:02:14] "GET /api/assets/model/environment/Charlie%20(Ops%20View)/asset/(Charlie)%20Air%20MEDEVAC?session_id=6f2J6MGkB5ZKdulWkf1rO76XUtREWrft&hide_concerns=0 HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [30/Mar/2018 19:02:24] "GET /api/dimensions/table/asset/environment/All%20Systems%20(Overview)?session_id=6f2J6MGkB5ZKdulWkf1rO76XUtREWrft HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [30/Mar/2018 19:03:15] "GET /api/assets/model/environment/All%20Systems%20(Overview)/asset/all?session_id=6f2J6MGkB5ZKdulWkf1rO76XUtREWrft&hide_concerns=0 HTTP/1.1" 200 -

### Steps to reproduce the behaviour
This error is probably from having too long titles somewhere, but seems fine with concerns turned off, which they normally are.

### Version of CAIRIS
Git pull around 01:30 31 March 18

### Operating Systems / Hardware 
As previous

**Comment by failys** [comment]
It's not pretty, and takes longer than it should - but I can't reproduce this problem on the latest version of CAIRIS.

With any changes that entail database table changes, it's a good idea to run the quick_setup.py script again.  Try this and see if you can reproduce the problem.  If you can, I'll re-open this issue.

**Comment by D-Dev** [comment]
Hi Shamal

Ok no problem, I didn't think about re-running the script (probably because
I'm too paranoid I'll really break it) but I'll give it a go.

Kind Regards
Duncan

**Comment by failys** [comment]
The quick_setup.py script is pretty robust, and it's the quickest way of dropping the database, re-creating the database objects, and re-creating your user account.  Just don't forget to export your model before running the script; you can re-import it again once you've finished.

**Comment by D-Dev** [comment]
Following on from that, in the scenario of editing the xml file (e.g. to
get rid of my two floaters) if I then imported the edited file back in,
would I need to re-run scripts in that scenario?

I've been reluctant to do that, again in case I break something, but
planned to try it anyway, but test it in a different CAIRIS/ laptop. Would
I need to run a script then too, or is it literally when there's been a
functionality update  (e.g. GDPR)?

And, are there any other little steps or tips i would benefit from doing
more often? E.g. I now usually do a Pull every other day just in case.

**Comment by failys** [comment]
Assuming you've exported your model file, just do a git pull, re-run quick_setup.py and re-import your script.  That's it.

If you really want to save time then you could run the cimport.py script to directly import the model file without using the GUI.  Assuming your current working directory is the cairis/bin directory (same directory cairisd.py is in), your account is called 'test' and your model is /tmp/mymodel.xml then you would run:

`./cimport.py --user=test --database=test_default --type all --overwrite 1 /tmp/mymodel.xml`

**Comment by D-Dev** [comment]
Ok, thanks :-)

**Comment by D-Dev** [comment]
Just to confirm, this solution worked fine and solved the data subject
scenarios :-)
