### ISSUE TITLE
Local CAIRIS Vulnerability issues

### ISSUE THREAD

**Issue by MLaverton** [failys/cairis#234]
### Expected behaviour
Adding a vulnerability creates the vulnerability without issue

### Actual behaviour
Vulnerability does not save and an error message is instead displayed:
![image](https://user-images.githubusercontent.com/33700030/38992460-b5e6268c-43d8-11e8-9ab1-16427dd01f6a.png)

### Steps to reproduce the behaviour
Using Firefox on Linux Ubuntu. Create a database, add all necessary aspects to be able to create a vulnerability, then make a vulnerability such as below:
![image](https://user-images.githubusercontent.com/33700030/38992698-6ce57680-43d9-11e8-9a46-fbe50ae91c62.png)

### Version of CAIRIS
CAIRIS 1.5.3

### Operating Systems / Hardware 
Linux - Ubuntu 10

**Comment by failys** [comment]
I’ve imported the model, but can’t reproduce your problem on Firefox [albeit on Mac OS not Linux].

Can you please try pulling the latest updates from github and tried running the quick_setup.py script?  

If you still get the same problem, can you please try using a different browser?

**Comment by failys** [comment]
Closing until this can be reproduced.
