### ISSUE TITLE
Importing to CAIRIS using Gt2pc

### ISSUE THREAD

**Issue by andymmanga** [failys/cairis#236]
### Expected behaviour
Conversion of CSV file to XML models fof CAIRIS import

### Actual behaviour
I am running the command "python gt2pc.py --context Default --originator AM --concepts concepts.csv --propositions propositions.csv --characteristics characteristics.csv --narratives narrative.csv pc.xml".

I get the error File "gt2pc.py", line 55, in main
    edCode,pNo = pId.split('-')
ValueError: need more than 1 value to unpack".

### Operating Systems / Hardware 

Ubuntu 16

**Comment by failys** [comment]
I’ve just run your command through the debugger.  The problem seems to be that your quotations in propositions don’t have a hyphen between the concept code and the number.  For example, ‘SA1’ should be ‘SA-1’.
