### ISSUE TITLE
Risk Model not showing some risk calculations

### ISSUE THREAD

**Issue by D-Dev** [failys/cairis#251]
### Expected behaviour
When in a Risk model, you can click on any Risk text and the sidebar information pops out showing the risk calculation below.

### Actual behaviour
(NOTE: This could be how I'm linking things across systems/environments?)
When in a Risk model, when clicking some risks in any of the environments, the sidebar has no risk calculation (e.g. in 'Bravo' view, FM-TOC Radio Comm's Interception disclosure). There may be a logical reason for this, but I haven't quite figured out if it's me or CAIRIS.

### Steps to reproduce the behaviour
This uses the data from MMN201805[07 or 12]
Once loaded, run the Risk model, and view by any of the environements. 

### Version of CAIRIS
Current

### Operating Systems / Hardware 
As previous

**Comment by failys** [comment]
This has been fixed.
