### ISSUE TITLE
Using Persona Images - How to share the file with images to stakeholders?

### ISSUE THREAD

**Issue by D-Dev** [failys/cairis#254]
### Expected behaviour
Please note, this may not be an issue, it's more of a process question, and may be user misunderstanding.

The scenario is, I want to add images to a persona, so I left-click the avatar and a pop-out is given to upload an image. Select the image from anywhere on your computer (or in my case Linux in the VM), then click upload/ok etc. A bar flashes in the avatar but no image displays. Ok, so go to the /tmp folder in Linux, then I see two copies of the image. Not sure which one I want, but copy both and paste them in the default image folder for CAIRIS (e.g. home/cairisuser/cairis/img). Go back to UX/Personas, click a persona and great it shows the image.

### Actual behaviour
The question is that I may want to share this (MMN) model with other stakeholders. I can export the model as an xml file and save a copy to somewhere like Github. This file can then be downloaded by the stakeholder and be imported into their CAIRIS. 

As this file now uses persona images, what would the stakeholder process be to include these in their model? For example, do I upload both copies of the (copy/pasted) image to Github? Should the stakeholder then place those copies in a folder using the same file path (assuming the are also a .../cairisuser/...) or should they at least have an img folder inside the CAIRIS folder like me - or is there another way this should be done by the stakeholder, for example, the stakeholder simply adds the images to personas themselves (in a similar way that I did)?

### Steps to reproduce the behaviour
It was when I was uploading MMN20180512 and the images to Github that I thought about this, and wondered how and what the stakeholder would now do in this scenario, and whether they have to re-add the persona images, or if their CAIRIS knew the image files were already linked and the images need to placed somewhere specific for them to link without error etc.

### Version of CAIRIS
Current

### Operating Systems / Hardware 
As previous

**Comment by failys** [comment]
Did you check that upload_dir and default_image_dir point to the same place?

**Comment by failys** [comment]
The quick fix would be to (i) update cairis.cnf as indicate above, (ii) make sure the images are in the right location, (iii) restart cairisd

**Comment by D-Dev** [comment]
Thank you. The cnf was the obvious choice, but I was being overly cautious
with that idea in case something in the background didn't work because of
the change. So I was making sure I do things the the right way.
