### ISSUE TITLE
Importing from Trello

### ISSUE THREAD

**Issue by D-Dev** [failys/cairis#259]
### Expected behaviour
(Apologies, this may be the user being silly again)
Having captured factoids using PersonaHelper that created Document References, I can use these to manually create and view a persona characteristic model (e.g. as with Filed Medic in MMN20180515).
I can then follow the CAIRIS-Trello video to Export to Trello, creating uncategorised factoids. I then follow the Grounds and Warrant process (I think following the steps correctly), which should then enable and Import from Trello into CAIRIS creating the related persona characteristic(s).

### Actual behaviour
It doesn't import and CAIRIS gives a similar error in the browser and terminal.
The error suggests things are missing, although in the video the only things that seemed relevant were the Board names using the persona name, the characteristic title, it's grounds and warrant factoids, imported into the same named persona.

ERROR:cairisd:[400] 400: One or more parameters are missing or invalid. Please check your request if it contains all the required parameters.
Required parameters:
* theWarrant
* theModQual
* theVariable
* theCharacteristic
* theRebuttal
* thePersonaName
* theGrounds
* theCharacteristicSynopsis
INFO:werkzeug:127.0.0.1 - - [16/May/2018 14:03:16] "POST /api/persona_characteristics?session_id=u1CLJNK7qwA90xCfyzznuoGSBBMWgYy6 HTTP/1.1" 400 -

### Steps to reproduce the behaviour
I tried this is many ways, but can't figure out where I'm missing the step. I've attached some screenshots showing 2 of 3 ways of last testing this.
Firstly, once dropping the factoids into groups giving them each a characteristic name then using a colon before writing 'attitudes' etc. I have no uncategorised factoids left, and have named characteristics with various combinations of Ground and Warrants (e.g. some with one or more warrants etc) and one with a rebuttal. They cover the range of skills, motivations, attitudes etc. This did not work.
Second, I removed characteristics leaving only a selection of attitudes. This did not work.
Before the next test, I logged out and reset everything, cleared browser cache, then logged back in to Trello and CAIRIS. I then chose a different persona and only included one 'activity' characteristic with one grounds and warrant. I made sure I was in the persona on the activity tab in case that's relevant, and to almost duplicate what the video showed - whereas in test 1 and 2 I'm adding multiple characteristics. Then import again, but receive the same error. [trello error.docx](https://github.com/failys/cairis/files/2011027/trello.error.docx)

Where did I go wrong? :-)

### Version of CAIRIS
Current

### Operating Systems / Hardware 
Win7-VMware-Ubuntu17-Chrome

**Comment by failys** [comment]
I've just pushed an update that fixes this.  Pull the latest sources and clear your browser's cache/history and you should be good to go.

**Comment by D-Dev** [comment]
Hi there, I can confirm with much joy, it works with no problems now,
although I shall try other different combinations to test it further later.
Thank you again!
