### ISSUE TITLE
Setting cairis initial user in quick_setup as username root crashes when logging in

### ISSUE THREAD

**Issue by nebloc** [failys/cairis#285]
### Expected behaviour
Either quick_setup dissallow the user to be called root, or root to be able to log in normally

### Actual behaviour
Logging in as account created in quicksetup, username=root, on the web console (started with cairisd.py runserver) causes the process to crash with no password error.
```
OperationalError: (_mysql_exceptions.OperationalError) (1045, "Access denied for user 'root'@'localhost' (using password: NO)") (Background on this error at: http://sqlalche.me/e/e3q8)
```
### Steps to reproduce the behaviour
* Clone repo
* Install all requirements
* Run quickstart
* Set mysql root password (as root in this case)
* Set inital username to root
* Set initial password to root (setting it as something else did not effect) 
* Run ~/cairis/cairis/bin/cairisd.py runserver
* Open port 7071 in browser
* Attempt to log in as user root
 
### Version of CAIRIS
Shallow clone of commit: 4339daf - Master branch
Version in console: 1.6.8

### Operating Systems / Hardware 
Ubuntu 16.05 Server
Virtualbox VM - 2048MB Ram and 2 CPUs

**Comment by failys** [comment]
The merged pull request and the documentation update should address this.
