### ISSUE TITLE
Loading Multiple Exemplars

### ISSUE THREAD

**Issue by andymmanga** [failys/cairis#31]
Could it be possible to adapt Cairis to load more than one exemplar at a time?

**Comment by failys** [comment]
By that, I assume you mean more than one CAIRIS model at a time?  i.e. 

$ cimport.py --type all --overwrite 1 --image_dir . NeuroGrid.xml  NeuroGridSpecificThreats.xml

where 'NeuroGrid.xml' is a complete model, and 'NeuroGridSpecificThreats.xml' contains some additional threat we want to add to the model.

I think the question is what would the above offer that running two cimport commands doesn't, i.e.

$ cimport.py --type all --overwrite 1 --image_dir . NeuroGrid.xml  
$ cimport.py --type all --overwrite 1 --image_dir . NeuroGridSpecificThreats.xml

**Comment by failys** [comment]
Closing.  I think this something that can be trivially scripted.
