### ISSUE TITLE
Cannot import organised factoids from Trello into CAIRIS

### ISSUE THREAD

**Issue by OlleHa** [failys/cairis#312]
### Expected behaviour
Have signed into my account on the Trello API. I have selected my board and want to import the factoids from here into CAIRIS.

### Actual behaviour
It shows my boards but when I click "import" CAIRIS does nothing. It shows no error message or success. The factoids do not show up in CAIRIS

### Steps to reproduce the behaviour
- Link Trello account to cairis
- select board
- click "import"

### Version of CAIRIS
V1.7.1

### Operating Systems / Hardware 
PG13 CAIRIS VM 
![img_2599](https://user-images.githubusercontent.com/44779610/48008690-10a96d00-e112-11e8-85cd-426c68972d24.jpg)

**Comment by failys** [comment]
I've just tried reproducing the problem and can't.  Some things to check:

* Have you created a skeleton persona in CAIRIS, e.g. Alice  .  Don't worry about the content for now.  There just needs to be a persona object created.
* Is the Trello board the same name as the persona the imported persona characteristics will be associated with, e.g. Alice
* Are the list names postfixed with a colon and the behavioural variable that persona characteristic will be associated with.  For example, if the list is called 'someChar' and is associated with activities then it's name should be 'someChar: activities'
* Have you added a grounds, warrant, or rebuttal label to each card.

**Comment by failys** [comment]
If you still get problems, can you please check your browser's javascript console to see if any errors have been reported there.
