### ISSUE TITLE
Unable to Generate documentation

### ISSUE THREAD

**Issue by MatthewPWatson** [failys/cairis#313]
### Expected behaviour

System - Documentation - Personas / Requirements - Output type PDF or RTF.
Should export to either.

### Actual behaviour
Clicking "generate" begins a spinning cog image, this stays on screen and never results in a downloaded file. Have tried multiple times and continue to wait after 30 minutes.
### Steps to reproduce the behaviour
Cairis with data to create personas.. go to system, documentation, then click type and output type.. generate.

### Version of CAIRIS

V1.7.1

### Operating Systems / Hardware 

VMWare with Ubuntu 18.04.1, 8 GB ram allocated.
![image](https://user-images.githubusercontent.com/17931666/48303608-fb628300-e503-11e8-8634-3290f3b8c708.png)

**Comment by failys** [comment]
I can generate documentation from the sample NeuroGrid and ACME Water models without any problem on the latest version of CAIRIS.  Can you?  If you can but can't with your model, can you please upload the simplest model that you can that doesn't work?
