### ISSUE TITLE
Cannot export model

### ISSUE THREAD

**Issue by OlleHa** [failys/cairis#315]
### Expected behaviour
Export model from CAIRIS successfully

### Actual behaviour
Blue loading wheel will not go away, model does not export.

### Steps to reproduce the behaviour
click "export model" under "system"

### Version of CAIRIS
1.7.2

### Operating Systems / Hardware 
Mac OS Mojave 10.14.1

**Comment by OlleHa** [comment]
Issue was fixed by removing ampersand in "authors" section of a task.

**Comment by failys** [comment]
Thanks for the issue.  Can you please indicate where the & was.  Did you manually add this to the XML file before import, was it added via one of the CAIRIS forms, or via some other source (e.g. importing a board from Trello or using the persona helper)

**Comment by OlleHa** [comment]
It was added in the "authors" field in the CAIRIS new task form.

**Comment by failys** [comment]
thanks

**Comment by OlleHa** [comment]
No problems.
