### ISSUE TITLE
Can't make session

### ISSUE THREAD

**Issue by D-Dev** [failys/cairis#325]
### Expected behaviour
CAIRIS Loads

### Actual behaviour
Oops. I did a gitpull, but CAIRIS won't load now suggesting a browser error that can't make a session.
I did run the quick_setup script just in case that helped clear anything, but it still won't play ball.

### Steps to reproduce the behaviour
Did a git pull this in past half hour

**Comment by failys** [comment]
Have you tried removing your cookies and browser cache?

**Comment by D-Dev** [comment]
Yep, I've done it a couple of times in FF and Chrome, but didn't help.

**Comment by failys** [comment]
Strange - nothing has changed recently, so the problem is either (i) browser cache related or (ii) something about the model . Can you please upload the model so I can take a look?

**Comment by D-Dev** [comment]
I'm not sure why, the problem seems have to resolved itself.

**Comment by D-Dev** [comment]
Thank you/sorry!
