### ISSUE TITLE
Error 404 when clicking link between two objects in graphical representation

### ISSUE THREAD

**Issue by RichPayne** [failys/cairis#50]
### Actual behaviour
Produces a serialized error.
{
    "code": 404, 
    "message": "The provided role name could not be found in the database. You have requested this URI [/api/roles/name/attacker] but did you mean /api/roles/name/<string:name> or /api/roles/name/<string:name>/properties or /api/goals/name/<string:name> ?", 
    "status": "Object not found"
}

### Steps to reproduce the behaviour
When you view the risk model and click the line between two elements (in this case the role and the attacker) it produces an error.

### Operating Systems / Hardware 
Ubuntu VPS (2gb RAM)

**Comment by failys** [comment]
The problem here seems to be that, when generating the model, as redundant URL is being added to pydot.Edges.  Removing the URL seems to have fixed this problem, so I'm closing this issue.  Please re-open / comment if you spot similar issues elsewhere though.
