### ISSUE TITLE
Asset descriptions in risk model

### ISSUE THREAD

**Issue by ivanflechais** [failys/cairis#51]
### Expected behaviour
Assets should display the security properties even if they are null. In practice this means that assets with e.g. no confidentiality should display an empty row.

### Actual behaviour
Security properties that have no value are not displayed visually. This means that you need to rely on the colour of the boxes to determine whether it is a confidentiality, integrity, availability, or accountability property.

### Steps to reproduce the behaviour
Look at the risk model.

**Comment by failys** [comment]
Fixed in latest released
