### ISSUE TITLE
Issue importing and exporting a model file

### ISSUE THREAD

**Issue by 05smichaelc** [failys/cairis#57]
When trying to export a model I get the following error message:

{
    "code": 400, 
    "message": "One or more parameters are missing or invalid. Please check your request if it contains all the required parameters.\nRequired parameters:\n* session_id", 
    "status": 400
}

It seems to happen when I add a persona and or roles.
The error message doesn't always come up after a persona or role is added and will allow my to export the model.xml file however when trying to import that very same file later it never gets past the loading screen.

I have looked at the model.xml file that it allowed me to download and when deleting everything in between the usability tags it is able to load the model. 

Any help would be greatly appreciated

[Archive.zip](https://github.com/failys/cairis/files/903230/Archive.zip)

**Comment by failys** [comment]
Seems to be a character encoding problem.  

As a quick workaround, replace "doesn't" with "does not" and the problems should go away. This is definitely a bug though, so I'll look into this.

**Comment by failys** [comment]
I've just pushed a fix that deals with this problem.  This should be incorporated into the docker container used by the live demo tomorrow morning.
