### ISSUE TITLE
Adding multiple threats

### ISSUE THREAD

**Issue by 05smichaelc** [failys/cairis#59]
When adding a Threat in CAIRIS, leaving the Tags field blank, it will be assigned "". If another threat is created it will also be assigned the same tag. This causes a primary key error when importing the model.

Apologies if this has been addressed in a newer version.

**Comment by failys** [comment]
Just pushed a fix for this problem.   The container on docker hub should be updated for this fix in the next hour or so, and the live demo should be updated tomorrow morning.
