### ISSUE TITLE
Stored procedure 'delete_vulnerability' referring to non-existing column

### ISSUE THREAD

**Issue by RobinQuetin** [failys/CAIRIS#9]
In the stored procedure 'delete_vulnerability' there is an SQL statement which refers to a non-existing column in the database. This makes it impossible to delete any vulnerability.

The SQL statement which contains the invalid reference is the following:
``` delete from component_vulnerability_target where threat_id = threatId; ```
...where threat_id is the non-existing column.

**Comment by failys** [comment]
I've fixed this, and a slew of other problems deleting other objects like assets and vulnerabilities as well.

**Comment by RobinQuetin** [comment]
All my unit tests pass now so the issue should be resolved. Thank you!
